#18 Add ability to change hand color.
nativesintech/MMIWG2S pull request #67
Opened 2021-03-07 07:47 UTC by Mehequanna

Add color change buttons. Just need to change their sizes.

Have buttons update in size when tapped.

Update hands to use old version.

2021-03-08 03:05 UTC, kjanderson2 requested changes
You're gonna want to hide these buttons when after the capture occurs or you end up having them weirdly below the back button.

2021-03-08 04:02 UTC, Mehequanna commented
> You're gonna want to hide these buttons when after the capture occurs or you end up having them weirdly below the back button.

@kjanderson2 Oh my gosh, thank you for catching that! How did I forget that?

2021-03-08 04:57 UTC, Mehequanna commented on Android/app/src/main/res/layout/activity_mmiw_ar.xml
> +    <Button
@kjanderson2 do you know what I can do to complete this task. I'm all for accessibility, but I don't know how to name or label a button.

2021-03-29 00:22 UTC, kjanderson2 commented on Android/app/src/main/res/layout/activity_mmiw_ar.xml
> +    <Button
This is odd... a contentDescription is an accessible label so I'm not sure what more it wants from you there... Is accesslint made for Android? Seems odd that it's not recognizing that as the right way to do accessibility for a button

2021-03-29 00:26 UTC, kjanderson2 approved these changes
Tested it out and it works great! I still like the red hand best though :)

2021-03-29 05:14 UTC, merged