Android/45 share with us
nativesintech/MMIWG2S pull request #87
Opened 2021-05-18 04:31 UTC by kjanderson2

Added share with us screen. It's not perfect and I'd love to add a spinner while it's capturing the image but I think it does everything it is supposed to!

2021-05-18 06:16 UTC, Mehequanna requested changes
This looks and works great! The only change I'm requesting is the share button is not red. Are you seeing that?


![Screenshot_20210517-230759](https://user-images.githubusercontent.com/10900996/118600515-f54d5d00-b765-11eb-9210-025e9c074c45.png)

2021-05-18 06:16 UTC, Mehequanna commented on Android/app/src/main/java/com/mehequanna/mmiw/MmiwActivity.kt
> +            if (resultCode == RESULT_OK) {
Could this be `if (resultCode == RESULT_OK || resultCode == RESULT_CANCLED)`?

2021-05-18 06:16 UTC, Mehequanna commented on Android/app/src/main/java/com/mehequanna/mmiw/MmiwActivity.kt
> +    private fun resetToCapturing() {
🔥 this is great!

2021-05-18 06:16 UTC, Mehequanna commented on Android/app/src/main/java/com/mehequanna/mmiw/MmiwActivity.kt
> +    private fun fadeOutView(view: View?, onAnimationEnd: (() -> Unit)? = null) {
These are slick :)

2021-05-18 19:48 UTC, kjanderson2 commented
Weirdly it's having trouble being red and also having the ripple effect. I updated it ot be red but now it doesn't have the touch effect. I will keep noodling on that but at least we can get that in

2021-05-19 01:14 UTC, Mehequanna reviewed
One last thing, sorry :/

2021-05-19 01:14 UTC, Mehequanna commented on Android/app/src/main/res/layout/share_with_us_layout.xml
> +        android:focusableInTouchMode="true"
With this in here, I have to touch the button twice. I removed it and it seems to work with ripple. Is that the same for you?

2021-05-19 01:16 UTC, Mehequanna approved these changes
This looks great! If we can get the share button to only be tapped once, feel free to merge :)

2021-05-19 16:36 UTC, merged